version: '2'
services:
  node:
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - REDIS_HOST=redis
    ports:
      - "8001:8001"
      - "9229:9229"
    networks:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis
networks:
  redis:
    driver: bridge
