version: '2'
services:
  node:
    build: .
    ports:
      - "8001:8001"
    networks:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis
networks:
  redis:
    driver: bridge
